#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the bitcoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
	
    0xa1141c95,0x91194d2d,
};

static const uint8_t chainparams_seed_test[] = {
	
    0x0,
};
#endif // BITCOIN_CHAINPARAMSSEEDS_H
